version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - ./postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    env_file:
      - ./pgAdmin4.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres_network
    volumes:
      - pgadmin_pgadmin:/var/lib/pgadmin
  
  bookstore:
    image: bookstore:latest
    container_name: bookstore
    restart: always
    env_file:
      - Source/BookStore.WebAPI/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - postgres_network
    volumes:
      - ./bookstorecert.pfx:/https-certs/bookstorecert.pfx

networks:
  postgres_network:

volumes:
  postgres_data:
  pgadmin_pgadmin:
  pgadmin_servers:
